# Times should be expressed in military time and in string form, (Hour:Minutes or Hour:Minutes:Seconds) 

# Time the internet will be cut off
shutdowntimes:
  - "19:52:00"
  - "20:00:00"
  - "21:30:00"
  - "16:00:00"
  - "3:00:00"
  - "23:40:20"
  - "0:00:00"
  - "0:30:00"
  - "0:45:00"
  - "0:57:30"
  - "2:00:00"

uptimes:
  - "5:00:00"
  - "15:14:00"
  - "16:00:00"
  - "17:00:00"
# Time with which determines when a new day is in streak terms
streakshift: "4:00"
ethernet:
  - "Ethernet"
  - "Ethernet 2"
  - "NordLynx"
debug: true