# Times should be expressed in military time and in string form, (Hour:Minutes or Hour:Minutes:Seconds) 

host: "127.0.0.1"

port: 65432

# Time the internet will be cut off
shutdown_times:
  - "21:18:50"
  - "19:51:00"
  - "21:30:00"
  - "16:00:00"
  - "3:00:00"
  - "23:40:20"
  - "0:00:00"
  - "0:30:00"
  - "0:45:00"
  - "0:57:30"
  - "2:00:00"

enforced_shutdown_times:
  - "16:40:00"
  - "1:00:00"
  - "2:00:00"
  - "3:00:00"
  - "4:00:00"

up_times:
  - "5:00:00"
  - "15:14:00"
  - "16:00:00"
  - "17:00:00"

# Time with which determines when a new day is in streak terms
streak_shift: "4:00"

ethernet:
  - "Ethernet"
  - "Ethernet 2"
  - "NordLynx"

debug: true