# Times should be expressed in military time and in string form, (Hour:Minutes or Hour:Minutes:Seconds) 

host: "127.0.0.1"

port: 65432

# Time the internet will be cut off
shutdown_times:
  - "23:00:00"
  - "0:00:00"
  - "0:30:00"
  - "0:45:00"
  - "0:57:30"

enforced_shutdown_times:
  - "1:00:00"
  - "2:00:00"

up_times:
  - "5:00:00"

# Time with which determines when a new day is in streak terms
streak_shift: "12:34"

ethernet:
  - "Ethernet"
  - "Ethernet 2"
  - "NordLynx"

military_time: false
debug: false