# Config Class for Internet Manager's Server Component 
# All Times must be in military time 
# By Justin Hahn 2024 [https://github.com/HahnJustin] 

host: "127.0.0.1"
port: 65432

key: sWXO8LvX0FaQgNAbDckjy32kfBQDPtvODAVLhcc7GgM=

# Time the internet will be cut off
shutdown_times:
  - "23:00:00"
  - "23:30:00"
  - "23:45:00"
  - "23:52:30"
  - "0:00:00"

enforced_shutdown_times:
  - "0:05:00"

up_times:
  - "4:00:00"

ethernet:
  - "Ethernet"
  - "Ethernet 2"
  - "NordLynx"

# Time with which determines when a new day is in streak terms
streak_shift: "3:00"

military_time: false

sound_on: true

warning_minutes: 15