# Config Class for Internet Manager's Server Component 
# All Times must be in military time 
# By Justin Hahn 2024 [https://github.com/HahnJustin] 

host: "127.0.0.1"
port: 65432

# Time the internet will be cut off
shutdown_times:
  - "23:00:00"
  - "0:00:00"
  - "0:30:00"
  - "0:45:00"
  - "0:57:30"

enforced_shutdown_times:
  - "1:00:00"
  - "2:00:00"

up_times:
  - "5:00:00"

ethernet:
  - "Ethernet"
  - "Ethernet 2"
  - "NordLynx"

# Time with which determines when a new day is in streak terms
streak_shift: "4:00"

military_time: false

sound_on: true

warning_minutes: 15