name: "Build Executables"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-internet-manager:
    name: "Build Gui Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller src/internet_manager.spec

    - uses: actions/upload-artifact@v4
      with:
        name: internet_manager
        path: src/dist/windows
        retention-days: 1

  build-server:
    name: "Build Server Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller src/internet_manager.spec

    - uses: actions/upload-artifact@v4
      with:
        name: server
        path: src/dist/windows
        retention-days: 1