name: "Build Executables"

on:
  pull_request:
    branches: [ main ]

jobs:
  build-internet-manager:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src
        spec: internet_manager.spec
        requirements: "requirements/requirements-gui.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: internet_manager
        path: src/dist/windows
        retention-days: 1

  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src
        spec: server.spec
        requirements: "requirements/requirements-server.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: src/dist/windows
        retention-days: 1