name: "Build Executables"

on:
  pull_request:
    branches: [ main ]

jobs:
  build-internet-manager:
    name: "Build Gui Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: internet_manager.spec
        requirements: requirements/requirements-gui.txt

    - uses: actions/upload-artifact@v4
      with:
        name: internet_manager
        path: src/dist/windows
        retention-days: 1

  build-server:
    name: "Build Server Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: server.spec
        requirements: requirements/requirements-server.txt

    - uses: actions/upload-artifact@v4
      with:
        name: server
        path: src/dist/windows
        retention-days: 1