name: "Create Pre-Release"

on:
  push:
    branches: [ main ]

jobs:
  build-internet-manager:
    name: "Build Gui Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src
        spec: internet_manager.spec
        requirements: "requirements/requirements-gui.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: internet_manager
        path: src/dist/windows
        retention-days: 7

  build-server:
    name: "Build Server Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src
        spec: server.spec
        requirements: "requirements/requirements-server.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: src/dist/windows
        retention-days: 7

  pre-release:
    name: "Create Pre Release"
    runs-on: "ubuntu-latest"
    needs: [build-internet-manager, build-server]
    steps:   
      - uses: actions/checkout@v2

      - name: Download All Artifacts
        uses: actions/download-artifact@v2
        with:
          path: src/dist/windows
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.exe
            config.yaml
            client-config.yaml