name: "Create Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build-internet-manager:
    name: "Build Gui Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: internet_manager.spec

    - uses: actions/upload-artifact@v4
      with:
        name: internet_manager
        path: src/dist/windows
        retention-days: 7

  build-server:
    name: "Build Server Executable"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: server.spec

    - uses: actions/upload-artifact@v4
      with:
        name: server
        path: src/dist/windows
        retention-days: 7

  tagged-release:
    name: "Create Tagged Release"
    runs-on: "ubuntu-latest"
    needs: [build-internet-manager, build-server]
    steps:   
      - uses: actions/checkout@v2

      - name: Download Server
        uses: actions/download-artifact@v4
        with:
          name: server

      - name: Download Gui
        uses: actions/download-artifact@v4
        with:
          name: internet_manager
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            *.exe
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}