name: "Create Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build-internet-manager:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src
        spec: internet_manager.spec
        requirements: "requirements/requirements-gui.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: internet_manager
        path: src/dist/windows
        retention-days: 7

  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src
        spec: server.spec
        requirements: "requirements/requirements-server.txt"

    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: src/dist/windows
        retention-days: 7

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: [build-internet-manager, build-server]
    steps:   
      - uses: actions/checkout@v2

      - name: Down All Artifacts
        uses: actions/download-artifact@v4

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.exe
                        config.yaml
            client-config.yaml